version: "3.9"

services:
  go-cqrs-elasticsearch:
    container_name: go-cqrs-elasticsearch
    restart: always
    networks:
      - go-cqrs
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.0
    environment:
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=elastic
      - xpack.security.enabled=true
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

  go-cqrs-postgree:
    container_name: go-cqrs-postgree
    image: postgres:14.1-alpine
    restart: always
    networks:
      - go-cqrs
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes: 
      - db:/var/lib/postgresql/data

  go-cqrs-redis:
    container_name: go-cqrs-redis
    image: redis:6.2-alpine
    restart: always
    networks:
      - go-cqrs
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - cache:/data

  go-cqrs-api:
    container_name: go-cqrs-api
    build: .
    command: ls
    restart: always
    networks:
      - go-cqrs
    environment:
      - PG_DATABASE_HOST=go-cqrs-postgree
      - PG_DATABASE_USERNAME=postgres
      - PG_DATABASE_PASSWORD=postgres
      - PG_DATABASE_NAME=postgres
      - PG_DATABASE_PORT=5432
      - PG_DATABASE_SSL_MODE=disable
      - LOG_LEVEL=debug # log_level=[debug, error]
      - ELASTICSEARCH_ADDRESSES=http://go-cqrs-elasticsearch:9200 # es addreses, delimit with ; to use multiple node
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=elastic
      - REDIS_HOST=go-cqrs-redis:6379
      - REDIS_PASSWORD=eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    ports:
      - 3000:3000
    volumes: 
      - db:/var/lib/postgresql/data


volumes:
  elasticsearch-data:
    driver: local
  db:
    driver: local
  cache:
    driver: local

networks:
  go-cqrs:
    driver: bridge
